definitions:
  domain.Unicorn:
    properties:
      capabilities:
        items:
          type: string
        type: array
      name:
        type: string
    type: object
  domain.UnicornProcess:
    properties:
      requestID:
        type: string
    type: object
info:
  contact: {}
  description: This is a API for UNICORN application
  title: UNICORN API
  version: "1.0"
paths:
  /api/unicorn:
    get:
      operationId: createUnicorn
      parameters:
      - description: /api/create-unicorn?amount=...
        in: query
        name: amount
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/domain.UnicornProcess'
        "400":
          description: Bad request
        "500":
          description: Error in process
      summary: Create Unicorn Process.
      tags:
      - Unicorn
  /api/unicorn/{id}:
    get:
      operationId: getUnicorn
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            items:
              $ref: '#/definitions/domain.Unicorn'
            type: array
        "400":
          description: Bad request
        "500":
          description: Error in process
      summary: Search Unicorn Process.
      tags:
      - Unicorn
swagger: "2.0"
